server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tobebought
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop # set to "update" when cleaning not needed
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        validation-mode: none
    show-sql: true
  main:
    web-application-type: servlet
